name: rich_notes_kp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  encrypt: 5.0.3
  archive: 3.4.10
  permission_handler: 11.2.0
  path: 1.8.3
  path_provider: 2.1.2
  flutter_quill: 9.2.8
  pdf: 3.10.7
  printing: 5.11.1
  quill_pdf_converter: 9.2.6
  quill_html_converter: 9.2.6
  flutter_quill_extensions: 9.2.6
  cached_network_image: 3.3.1
  desktop_drop: 0.4.4
  image_cropper: 5.0.1
  google_fonts: 6.1.0
  flutter_bloc: 8.1.3
  share_plus: 7.2.1
  freezed_annotation: 2.4.1
  hydrated_bloc: 9.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: monospace
      fonts: 
        - asset: assets/fonts/MonoSpace.ttf
    - family: serif
      fonts: 
        - asset: assets/fonts/Serif.ttf
    - family: sans-serif
      fonts: 
        - asset: assets/fonts/SansSerif.ttf
    - family: ibarra-real-nova
      fonts: 
        - asset: assets/fonts/IbarraRealNova-Regular.ttf
    - family: square-peg
      fonts: 
        - asset: assets/fonts/SquarePeg-Regular.ttf
    - family: nunito
      fonts: 
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: pacifico
      fonts: 
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: roboto-mono
      fonts: 
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SF-UI-Display
      fonts: 
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
  uses-material-design: true

